{
 "title": "VMs",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "custom_cpu_usage_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Disk Usage (%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "custom_disk_usage_percent", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Memory Usage (%)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "custom_memory_usage_percent", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Network Latency (ms)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "custom_network_latency", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "API Endpoint (Total Requests)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "http_requests_total", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}